LANGUAGES = [
    {"code": "en", "name": "English", "native": "English"},
    {"code": "ta", "name": "Tamil", "native": "தமிழ்"},
    {"code": "hi", "name": "Hindi", "native": "हिन्दी"},
    {"code": "ja", "name": "Japanese", "native": "日本語"},
    {"code": "ko", "name": "Korean", "native": "한국어"},
    {"code": "ar", "name": "Arabic", "native": "العربية"},
    {"code": "ru", "name": "Russian", "native": "Русский"},
    {"code": "de", "name": "German", "native": "Deutsch"},
    {"code": "fr", "name": "French", "native": "Français"},
    {"code": "es", "name": "Spanish", "native": "Español"},
    {"code": "pt", "name": "Portuguese", "native": "Português"},
    {"code": "it", "name": "Italian", "native": "Italiano"},
    {"code": "zh", "name": "Chinese (Simplified)", "native": "简体中文"},
    {"code": "zh-TW", "name": "Chinese (Traditional)", "native": "繁體中文"},
    {"code": "ml", "name": "Malayalam", "native": "മലയാളം"},
    {"code": "te", "name": "Telugu", "native": "తెలుగు"},
    {"code": "kn", "name": "Kannada", "native": "ಕನ್ನಡ"},
    {"code": "bn", "name": "Bengali", "native": "বাংলা"},
    {"code": "pa", "name": "Punjabi", "native": "ਪੰਜਾਬੀ"},
    {"code": "gu", "name": "Gujarati", "native": "ગુજરાતી"},
    {"code": "ur", "name": "Urdu", "native": "اردو"},
    {"code": "si", "name": "Sinhala", "native": "සිංහල"},
    {"code": "th", "name": "Thai", "native": "ไทย"},
    {"code": "vi", "name": "Vietnamese", "native": "Tiếng Việt"},
    {"code": "tr", "name": "Turkish", "native": "Türkçe"},
    {"code": "pl", "name": "Polish", "native": "Polski"},
    {"code": "nl", "name": "Dutch", "native": "Nederlands"},
    {"code": "sv", "name": "Swedish", "native": "Svenska"},
    {"code": "da", "name": "Danish", "native": "Dansk"},
    {"code": "no", "name": "Norwegian", "native": "Norsk"},
    {"code": "fi", "name": "Finnish", "native": "Suomi"},
    {"code": "el", "name": "Greek", "native": "Ελληνικά"},
    {"code": "cs", "name": "Czech", "native": "Čeština"},
    {"code": "sk", "name": "Slovak", "native": "Slovenčina"},
    {"code": "ro", "name": "Romanian", "native": "Română"},
    {"code": "bg", "name": "Bulgarian", "native": "Български"},
    {"code": "hr", "name": "Croatian", "native": "Hrvatski"},
    {"code": "sr", "name": "Serbian", "native": "Српски"},
    {"code": "sl", "name": "Slovenian", "native": "Slovenščina"},
    {"code": "uk", "name": "Ukrainian", "native": "Українська"},
    {"code": "he", "name": "Hebrew", "native": "עברית"},
    {"code": "fa", "name": "Persian", "native": "فارسی"},
    {"code": "id", "name": "Indonesian", "native": "Bahasa Indonesia"},
    {"code": "ms", "name": "Malay", "native": "Bahasa Melayu"},
    {"code": "tl", "name": "Filipino", "native": "Filipino"},
    {"code": "sw", "name": "Swahili", "native": "Kiswahili"},
    {"code": "af", "name": "Afrikaans", "native": "Afrikaans"},
    {"code": "am", "name": "Amharic", "native": "አማርኛ"},
    {"code": "az", "name": "Azerbaijani", "native": "Azərbaycan"},
    {"code": "be", "name": "Belarusian", "native": "Беларуская"},
    {"code": "bs", "name": "Bosnian", "native": "Bosanski"},
    {"code": "ca", "name": "Catalan", "native": "Català"},
    {"code": "ceb", "name": "Cebuano", "native": "Cebuano"},
    {"code": "co", "name": "Corsican", "native": "Corsu"},
    {"code": "cy", "name": "Welsh", "native": "Cymraeg"},
    {"code": "et", "name": "Estonian", "native": "Eesti"},
    {"code": "eu", "name": "Basque", "native": "Euskara"},
    {"code": "fy", "name": "Frisian", "native": "Frysk"},
    {"code": "ga", "name": "Irish", "native": "Gaeilge"},
    {"code": "gd", "name": "Scots Gaelic", "native": "Gàidhlig"},
    {"code": "gl", "name": "Galician", "native": "Galego"},
    {"code": "ha", "name": "Hausa", "native": "Hausa"},
    {"code": "haw", "name": "Hawaiian", "native": "ʻŌlelo Hawaiʻi"},
    {"code": "hmn", "name": "Hmong", "native": "Hmoob"},
    {"code": "ht", "name": "Haitian Creole", "native": "Kreyòl Ayisyen"},
    {"code": "hu", "name": "Hungarian", "native": "Magyar"},
    {"code": "hy", "name": "Armenian", "native": "Հայերեն"},
    {"code": "ig", "name": "Igbo", "native": "Igbo"},
    {"code": "is", "name": "Icelandic", "native": "Íslenska"},
    {"code": "jw", "name": "Javanese", "native": "Basa Jawa"},
    {"code": "ka", "name": "Georgian", "native": "ქართული"},
    {"code": "kk", "name": "Kazakh", "native": "Қазақ тілі"},
    {"code": "km", "name": "Khmer", "native": "ខ្មែរ"},
    {"code": "ku", "name": "Kurdish", "native": "Kurdî"},
    {"code": "ky", "name": "Kyrgyz", "native": "Кыргызча"},
    {"code": "la", "name": "Latin", "native": "Latina"},
    {"code": "lb", "name": "Luxembourgish", "native": "Lëtzebuergesch"},
    {"code": "lo", "name": "Lao", "native": "ລາວ"},
    {"code": "lt", "name": "Lithuanian", "native": "Lietuvių"},
    {"code": "lv", "name": "Latvian", "native": "Latviešu"},
    {"code": "mg", "name": "Malagasy", "native": "Malagasy"},
    {"code": "mi", "name": "Maori", "native": "Te Reo Māori"},
    {"code": "mk", "name": "Macedonian", "native": "Македонски"},
    {"code": "mn", "name": "Mongolian", "native": "Монгол"},
    {"code": "mr", "name": "Marathi", "native": "मराठी"},
    {"code": "mt", "name": "Maltese", "native": "Malti"},
    {"code": "my", "name": "Myanmar (Burmese)", "native": "မြန်မာ"},
    {"code": "ne", "name": "Nepali", "native": "नेपाली"},
    {"code": "ny", "name": "Chichewa", "native": "Chichewa"},
    {"code": "or", "name": "Odia", "native": "ଓଡ଼ିଆ"},
    {"code": "ps", "name": "Pashto", "native": "پښتو"},
    {"code": "rw", "name": "Kinyarwanda", "native": "Ikinyarwanda"},
    {"code": "sa", "name": "Sanskrit", "native": "संस्कृतम्"},
    {"code": "sd", "name": "Sindhi", "native": "سنڌي"},
    {"code": "sm", "name": "Samoan", "native": "Gagana Samoa"},
    {"code": "sn", "name": "Shona", "native": "chiShona"},
    {"code": "so", "name": "Somali", "native": "Soomaali"},
    {"code": "sq", "name": "Albanian", "native": "Shqip"},
    {"code": "st", "name": "Sesotho", "native": "Sesotho"},
    {"code": "su", "name": "Sundanese", "native": "Basa Sunda"},
    {"code": "tg", "name": "Tajik", "native": "Тоҷикӣ"},
    {"code": "tk", "name": "Turkmen", "native": "Türkmen"},
    {"code": "tt", "name": "Tatar", "native": "Татар"},
    {"code": "ug", "name": "Uyghur", "native": "ئۇيغۇرچە"},
    {"code": "uz", "name": "Uzbek", "native": "Oʻzbek"},
    {"code": "xh", "name": "Xhosa", "native": "isiXhosa"},
    {"code": "yi", "name": "Yiddish", "native": "ייִדיש"},
    {"code": "yo", "name": "Yoruba", "native": "Yorùbá"},
    {"code": "zu", "name": "Zulu", "native": "isiZulu"},
    {"code": "as", "name": "Assamese", "native": "অসমীয়া"},
    {"code": "bho", "name": "Bhojpuri", "native": "भोजपुरी"},
    {"code": "doi", "name": "Dogri", "native": "डोगरी"},
    {"code": "ee", "name": "Ewe", "native": "Eʋegbe"},
    {"code": "gn", "name": "Guarani", "native": "Avañeʼẽ"},
    {"code": "ilo", "name": "Ilocano", "native": "Iloko"},
    {"code": "kri", "name": "Krio", "native": "Krio"},
    {"code": "lg", "name": "Luganda", "native": "Luganda"},
    {"code": "ln", "name": "Lingala", "native": "Lingála"},
    {"code": "lus", "name": "Mizo", "native": "Mizo ṭawng"},
    {"code": "mai", "name": "Maithili", "native": "मैथिली"},
    {"code": "mni-Mtei", "name": "Meiteilon (Manipuri)", "native": "ꯃꯤꯇꯩꯂꯣꯟ"},
    {"code": "nso", "name": "Sepedi", "native": "Sepedi"},
    {"code": "om", "name": "Oromo", "native": "Afaan Oromoo"},
    {"code": "qu", "name": "Quechua", "native": "Runasimi"},
    {"code": "ti", "name": "Tigrinya", "native": "ትግርኛ"},
    {"code": "ts", "name": "Tsonga", "native": "Xitsonga"},
]


def get_language_name(code: str) -> str:
    for lang in LANGUAGES:
        if lang["code"] == code:
            return lang["name"]
    return code
